# Generated by Django 5.2.13 on 2026-04-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('run_status', models.CharField(choices=[('success', '✅ Success'), ('partial', '⚠️ Partial'), ('failed', '❌ Failed')], default='success', max_length=20)),
                ('total_found', models.IntegerField(default=0, help_text='Total leads found in this run')),
                ('new_saved', models.IntegerField(default=0, help_text='New leads saved (after dedup)')),
                ('duplicates_skipped', models.IntegerField(default=0, help_text='Duplicates that were skipped')),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scrape Log',
                'verbose_name_plural': 'Scrape Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title or lead heading', max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Full job description or details')),
                ('budget', models.CharField(blank=True, default='', help_text="Client budget range, e.g. '$500 - $1,000'", max_length=100)),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text="List of technologies, e.g. ['React', 'Node.js', 'PostgreSQL']")),
                ('url', models.URLField(help_text='Direct URL to the job posting or lead page', max_length=2000, unique=True)),
                ('source', models.CharField(choices=[('upwork', 'Upwork'), ('freelancer', 'Freelancer'), ('agency', 'Agency Website'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='other', help_text='Where this lead was scraped from', max_length=50)),
                ('client_name', models.CharField(blank=True, default='', help_text='Client or company name (if available)', max_length=200)),
                ('client_country', models.CharField(blank=True, default='', help_text='Client location/country', max_length=100)),
                ('posted_date', models.CharField(blank=True, default='', help_text='When the job was posted (as displayed on source)', max_length=100)),
                ('status', models.CharField(choices=[('unnotified', '🔵 Unnotified'), ('notified', '🟡 Notified'), ('contacted', '🟢 Contacted'), ('rejected', '🔴 Rejected'), ('applied', '🟣 Applied')], db_index=True, default='unnotified', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes about this lead')),
                ('telegram_message_id', models.BigIntegerField(blank=True, help_text='Telegram message ID for updating the sent alert', null=True)),
                ('content_hash', models.CharField(editable=False, help_text='SHA-256 hash of title+url for deduplication', max_length=64, unique=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scraped Lead',
                'verbose_name_plural': 'Scraped Leads',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['status'], name='idx_lead_status'), models.Index(fields=['source'], name='idx_lead_source'), models.Index(fields=['scraped_at'], name='idx_lead_scraped_at'), models.Index(fields=['status', 'source'], name='idx_lead_status_source')],
            },
        ),
    ]
