# Generated by Django 5.2.13 on 2026-04-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_add_fiverr_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedlead',
            name='source',
            field=models.CharField(choices=[('upwork', 'Upwork'), ('fiverr', 'Fiverr'), ('freelancer', 'Freelancer.com'), ('agency', 'Agency Website'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='other', help_text='Where this lead was scraped from', max_length=50),
        ),
    ]
