# Generated by Django 5.2.13 on 2026-04-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_add_freelancer_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('service_interested', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', '🆕 New'), ('contacted', '✅ Contacted'), ('qualified', '💎 Qualified'), ('lost', '❌ Lost')], default='new', max_length=20)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agency Lead',
                'verbose_name_plural': 'Agency Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, help_text='e.g., Services, Pricing, Technical', max_length=100, null=True)),
                ('order', models.IntegerField(default=0, help_text='Sorting order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='scrapedlead',
            name='source',
            field=models.CharField(choices=[('freelancer', 'Freelancer.com'), ('other', 'Other')], default='other', help_text='Where this lead was scraped from', max_length=50),
        ),
    ]
